### ISSUE TITLE
AssumeRole on the AwsProvider interface is supposed to be an array now

### ISSUE THREAD

**Issue by kevanslumin** [cdktf/cdktf-provider-aws-go#2]
I think `AssumeRole` on line 24 here: https://github.com/cdktf/cdktf-provider-aws-go/blob/main/aws/provider/provider_AwsProvider.go is supposed to be an array now.

This was changed upstream here: https://github.com/cdktf/cdktf-provider-aws/commit/bc10d04d63405770a9478b546b79dd427e5d112f#diff-509e5a7e694ada9ee232d998a18480cb322eecec8351eb36cd68633af5ef0970R187 where the AwsProviderAssumeRole is an array now.

Looks like a bunch of other items are supposed to be arrays now too.

It causes this error:

```
panic: Passed to parameter config of new @cdktf/provider-aws.provider.AwsProvider: Unable to deserialize value as @cdktf/provider-aws.provider.AwsProviderConfig | undefined
├── 🛑 Failing value is an object
│      { '$jsii.struct': [Object] }
╰── 🔍 Failure reason(s):
    ╰─ Key 'assumeRole': Unable to deserialize value as cdktf.IResolvable | array<@cdktf/provider-aws.provider.AwsProviderAssumeRole> | undefined
        ├── 🛑 Failing value is an object
        │      { '$jsii.struct': [Object] }
        ╰── 🔍 Failure reason(s):
            ├─ [as array<@cdktf/provider-aws.provider.AwsProviderAssumeRole>] Value is not an array
            ╰─ [as cdktf.IResolvable] Value does not have the "$jsii.byref" key
```

**Comment by xiehan** [comment]
Hi @kevanslumin, thanks for raising an issue! Unfortunately, the individual provider repos aren't the right place for this; it's impossible for our team to monitor all of them. (I'll look into turning off these Issues tabs to prevent this confusion in the future.)

I tried to transfer this issue to the main [hashicorp/terraform-cdk](https://github.com/hashicorp/terraform-cdk/) repo but it's not letting me, likely because it's a different org. Could you please [open a new issue there](https://github.com/hashicorp/terraform-cdk/issues/new?assignees=&labels=bug%2C+new%2C+pre-built+providers&template=bug-report-prebuilt-providers.md&title=) instead? Thanks!
